name: Hourly Crypto Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs at the top of every hour

permissions:
  contents: write

jobs:
  run-crypto-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run crypto_scan.py
        run: python crypto_scan.py

      - name: Commit and push if CSV changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add financial_data_v1.0_debug.csv financial_data_v1.0_debug.html
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          git diff --staged --quiet || git commit -m "Hourly update: crypto news and BTC price ($TIMESTAMP)"
          git push